services:
  mongo_db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"
    networks:
      my-network:

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: uvicorn main:app --host=0.0.0.0 --port=80
    ports:
      - "8000:80"
    depends_on:
      - mongo_db
    networks:
      my-network:

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      my-network:

networks:
  my-network:

volumes:
  mongo_db:
