services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: uvicorn main:app --host=0.0.0.0 --port=80
    ports:
      - "80:80"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb: {}
