services:
  mongo_db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"
    networks:
      my-network:
        ipv4_address: 172.18.0.2

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: uvicorn main:app --host=0.0.0.0 --port=80
    ports:
      - "8000:80"
    volumes:
      - ./backend:/appbackend
    depends_on:
      - mongo_db
    networks:
      my-network:
        ipv4_address: 172.18.0.3

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/appfrontend
    depends_on:
      - backend
    networks:
      my-network:
        ipv4_address: 172.18.0.4

networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

volumes:
  mongo_db:
  backend:
  frontend:
